linter changes

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -15,29 +15,24 @@ steps:
 
   - name: "gcr.io/cloud-builders/docker"
     entrypoint: "bash"
-    args:
-      [
-        "-c",
-        "docker pull us.gcr.io/$PROJECT_ID/relay:nightly || true"
-      ]
+    args: ["-c", "docker pull us.gcr.io/$PROJECT_ID/relay:nightly || true"]
 
   # Pull the image with the first build stage
   - name: "gcr.io/cloud-builders/docker"
     entrypoint: "bash"
-    args:
-      [
-        "-c",
-        "docker pull us.gcr.io/$PROJECT_ID/relay:deps || true"
-      ]
+    args: ["-c", "docker pull us.gcr.io/$PROJECT_ID/relay:deps || true"]
 
   # Build the first stage
   - name: "gcr.io/cloud-builders/docker"
     args:
       [
         "build",
-        "--target", "relay-deps",
-        "-t", "us.gcr.io/$PROJECT_ID/relay:deps",
-        "--cache-from", "us.gcr.io/$PROJECT_ID/relay:deps",
+        "--target",
+        "relay-deps",
+        "-t",
+        "us.gcr.io/$PROJECT_ID/relay:deps",
+        "--cache-from",
+        "us.gcr.io/$PROJECT_ID/relay:deps",
         ".",
       ]
 
@@ -46,58 +41,58 @@ steps:
     args:
       [
         "build",
-        "-t", "us.gcr.io/$PROJECT_ID/relay:nightly",
-        "-t", "us.gcr.io/$PROJECT_ID/relay:$COMMIT_SHA",
-        "--cache-from", "us.gcr.io/$PROJECT_ID/relay:deps",
-        "--cache-from", "us.gcr.io/$PROJECT_ID/relay:nightly",
+        "-t",
+        "us.gcr.io/$PROJECT_ID/relay:nightly",
+        "-t",
+        "us.gcr.io/$PROJECT_ID/relay:$COMMIT_SHA",
+        "--cache-from",
+        "us.gcr.io/$PROJECT_ID/relay:deps",
+        "--cache-from",
+        "us.gcr.io/$PROJECT_ID/relay:nightly",
         ".",
       ]
 
   # We push the image to GCR since the Sentry integration tests are polling
   - name: "gcr.io/cloud-builders/docker"
-    args:
-      [
-        "push",
-        "us.gcr.io/$PROJECT_ID/relay:$COMMIT_SHA"
-      ]
+    args: ["push", "us.gcr.io/$PROJECT_ID/relay:$COMMIT_SHA"]
 
   # On-premise Integration tests
-  - name: 'gcr.io/$PROJECT_ID/docker-compose'
-    entrypoint: 'bash'
+  - name: "gcr.io/$PROJECT_ID/docker-compose"
+    entrypoint: "bash"
     env:
-    - 'RELAY_IMAGE=us.gcr.io/$PROJECT_ID/relay:$COMMIT_SHA'
-    - 'SENTRY_TEST_HOST=http://nginx'
-    - 'CI=1'
+      - "RELAY_IMAGE=us.gcr.io/$PROJECT_ID/relay:$COMMIT_SHA"
+      - "SENTRY_TEST_HOST=http://nginx"
+      - "CI=1"
     args:
-    - '-e'
-    - '-c'
-    - |
-      mkdir self-hosted && cd self-hosted
-      echo "no" > .reporterrors
-      curl -L "https://github.com/getsentry/self-hosted/archive/master.tar.gz" | tar xzf - --strip-components=1
-      # The following trick is from https://stackoverflow.com/a/52400857/90297 with great gratuity
-      echo '{"version": "3.4", "networks":{"default":{"external":{"name":"cloudbuild"}}}}' > docker-compose.override.yml
-      ./install.sh
-      ./test.sh || docker-compose logs nginx web relay
+      - "-e"
+      - "-c"
+      - |
+        mkdir self-hosted && cd self-hosted
+        echo "no" > .reporterrors
+        curl -L "https://github.com/getsentry/self-hosted/archive/master.tar.gz" | tar xzf - --strip-components=1
+        # The following trick is from https://stackoverflow.com/a/52400857/90297 with great gratuity
+        echo '{"version": "3.4", "networks":{"default":{"external":{"name":"cloudbuild"}}}}' > docker-compose.override.yml
+        ./install.sh
+        ./test.sh || docker-compose logs nginx web relay
     timeout: 900s
 
-  - name: 'gcr.io/cloud-builders/docker'
-    secretEnv: ['DOCKER_PASSWORD']
-    entrypoint: 'bash'
+  - name: "gcr.io/cloud-builders/docker"
+    secretEnv: ["DOCKER_PASSWORD"]
+    entrypoint: "bash"
     args:
-    - '-e'
-    - '-c'
-    - |
-      # Only push to Docker Hub from master
-      [ "$BRANCH_NAME" != "master" ] && exit 0
-      docker push us.gcr.io/$PROJECT_ID/relay:nightly
-      echo "$$DOCKER_PASSWORD" | docker login --username=sentrybuilder --password-stdin
-      docker tag us.gcr.io/$PROJECT_ID/relay:$COMMIT_SHA getsentry/relay:$SHORT_SHA
-      docker push getsentry/relay:$SHORT_SHA
-      docker tag us.gcr.io/$PROJECT_ID/relay:$COMMIT_SHA getsentry/relay:$COMMIT_SHA
-      docker push getsentry/relay:$COMMIT_SHA
-      docker tag us.gcr.io/$PROJECT_ID/relay:$COMMIT_SHA getsentry/relay:nightly
-      docker push getsentry/relay:nightly
+      - "-e"
+      - "-c"
+      - |
+        # Only push to Docker Hub from master
+        [ "$BRANCH_NAME" != "master" ] && exit 0
+        docker push us.gcr.io/$PROJECT_ID/relay:nightly
+        echo "$$DOCKER_PASSWORD" | docker login --username=sentrybuilder --password-stdin
+        docker tag us.gcr.io/$PROJECT_ID/relay:$COMMIT_SHA getsentry/relay:$SHORT_SHA
+        docker push getsentry/relay:$SHORT_SHA
+        docker tag us.gcr.io/$PROJECT_ID/relay:$COMMIT_SHA getsentry/relay:$COMMIT_SHA
+        docker push getsentry/relay:$COMMIT_SHA
+        docker tag us.gcr.io/$PROJECT_ID/relay:$COMMIT_SHA getsentry/relay:nightly
+        docker push getsentry/relay:nightly
 
 images:
   [
@@ -107,13 +102,13 @@ images:
 timeout: 3600s
 options:
   # Run on bigger machines
-  machineType: 'E2_HIGHCPU_8'
+  machineType: "E2_HIGHCPU_8"
 secrets:
-- kmsKeyName: projects/sentryio/locations/global/keyRings/service-credentials/cryptoKeys/cloudbuild
-  secretEnv:
-    # This is a personal access token for the sentrybuilder account, encrypted using the
-    # short guide at http://bit.ly/2Pg6uw9
-    DOCKER_PASSWORD: |
-      CiQAE8gN7y3OMxn+a1kofmK4Bi8jQZtdRFj2lYYwaZHVeIIBUzMSTQA9tvn8XCv2vqj6u8CHoeSP
-      TVW9pLvSCorKoeNtOp0eb+6V1yNJW/+JC07DNO1KLbTbodbuza6jKJHU5xeAJ4kGQI78UY5Vu1Gp
-      QcMK
+  - kmsKeyName: projects/sentryio/locations/global/keyRings/service-credentials/cryptoKeys/cloudbuild
+    secretEnv:
+      # This is a personal access token for the sentrybuilder account, encrypted using the
+      # short guide at http://bit.ly/2Pg6uw9
+      DOCKER_PASSWORD: |
+        CiQAE8gN7y3OMxn+a1kofmK4Bi8jQZtdRFj2lYYwaZHVeIIBUzMSTQA9tvn8XCv2vqj6u8CHoeSP
+        TVW9pLvSCorKoeNtOp0eb+6V1yNJW/+JC07DNO1KLbTbodbuza6jKJHU5xeAJ4kGQI78UY5Vu1Gp
+        QcMK
