Add separate job for google registry

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -14,10 +14,6 @@ env:
 
 jobs:
   build:
-    # required for google auth
-    permissions:
-      contents: 'read'
-      id-token: 'write'
     timeout-minutes: 30
     strategy:
       matrix:
@@ -97,6 +93,34 @@ jobs:
           docker tag "$IMG_VERSIONED" ghcr.io/getsentry/relay:latest
           docker push $IMG_DEFAULT
           docker push ghcr.io/getsentry/relay:latest
+
+  push-prod-image:
+    needs: build
+    # required for google auth
+    permissions:
+      contents: 'read'
+      id-token: 'write'
+    timeout-minutes: 5
+    strategy:
+      matrix:
+        # the arm64 build takes too long, so disable for now
+        arch: [amd64]
+    env:
+      # GITHUB_SHA in pull requests points to the merge commit
+      IMG_VERSIONED: ghcr.io/getsentry/relay:${{ matrix.arch }}-${{ github.event.pull_request.head.sha || github.sha }}
+      IMG_PROD: us.gcr.io/sentryio/relay:${{ matrix.arch }}-${{ github.event.pull_request.head.sha || github.sha }}
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          submodules: recursive
+
+      - name: Pull built image
+        run: |
+          set -euxo pipefail
+          if docker pull -q "$IMG_VERSIONED"; then
+            echo "Could not pull built image!"
+            exit 1
+          fi
 
       - name: Google Auth
         id: auth
