refine error handling

diff --git a/.github/workflows/data-schemas.yml b/.github/workflows/data-schemas.yml
--- a/.github/workflows/data-schemas.yml
+++ b/.github/workflows/data-schemas.yml
@@ -11,7 +11,8 @@ jobs:
         with:
           toolchain: stable
       - run: make jsonschema
-      - env:
+      - name: commit and push
+        env:
           GITHUB_TOKEN: ${{ secrets.DATA_SCHEMAS_GITHUB_TOKEN }}
         run: |
           git config --global user.email "markus+ghbot@sentry.io"
@@ -20,13 +21,22 @@ jobs:
           cd sentry-data-schemas/
           mkdir -p ./relay/
           cp ../docs/event-schema/event.schema.json ./relay/event.schema.json
+          if git diff-files --quiet; then
+            echo "No changes"
+            exit 0
+          fi
+
+          echo "git commit"
           git add .
           git commit -m "getsentry/relay@$GITHUB_SHA"
+
           for i in 1 2 3 4 5; do
-            echo "Attempt $i"
+            echo "git push; Attempt $i"
             if git push; then
-              break
+              exit 0
             fi
 
             git pull --rebase
           done
+          echo "Failed to push"
+          exit 1
