ci: Sync metrics into sentry-docs

diff --git a/.github/workflows/data-schemas.yml b/.github/workflows/data-schemas.yml
--- a/.github/workflows/data-schemas.yml
+++ b/.github/workflows/data-schemas.yml
@@ -23,13 +23,51 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.DATA_SCHEMAS_GITHUB_TOKEN }}
         run: |
-          git config --global user.email "markus+ghbot@sentry.io"
+          git config --global user.email "ghbot@sentry.io"
           git config --global user.name "sentry-bot"
           git clone https://getsentry-bot:$GITHUB_TOKEN@github.com/getsentry/sentry-data-schemas
           cd sentry-data-schemas/
           mkdir -p ./relay/
           mv ../event.schema.json relay/event.schema.json
           git add relay/event.schema.json
+
+          echo "attempting commit"
+          if ! git commit -m "getsentry/relay@$GITHUB_SHA" ; then
+            echo "Stopping, no changes"
+            exit 0
+          fi
+
+          for i in 1 2 3 4 5; do
+            echo "git push; Attempt $i"
+            if git push; then
+              exit 0
+            fi
+
+            git pull --rebase
+          done
+
+          echo "Failed to push"
+          exit 1
+  metrics_docs:
+    name: Metrics Docs
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+      - uses: actions-rs/toolchain@v1
+        with:
+          toolchain: stable
+      - run: cargo run -p document-metrics > relay_metrics.json
+      - name: commit and push
+        if: github.ref == 'refs/heads/master'
+        env:
+          GITHUB_TOKEN: ${{ secrets.DATA_SCHEMAS_GITHUB_TOKEN }}
+        run: |
+          git config --global user.email "ghbot@sentry.io"
+          git config --global user.name "sentry-bot"
+          git clone https://getsentry-bot:$GITHUB_TOKEN@github.com/getsentry/sentry-docs
+          cd sentry-docs/
+          mv ../relay_metrics.json src/data/relay_metrics.json
+          git add src/data/relay_metrics.json
 
           echo "attempting commit"
           if ! git commit -m "getsentry/relay@$GITHUB_SHA" ; then
